# Generated by Django 4.2.7 on 2023-11-14 08:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nrb_data_api', '0002_rename_contact_biodata'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='DisabledNationalCouncil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_number', models.CharField(max_length=50)),
                ('nature_of_disability', models.CharField(choices=[('Hearing impairment', 'Hearing impairment'), ('Cerebral palsy', 'Cerebral palsy'), ('Vision impairment', 'Vision impairment'), ('Autistic Spectrum Disorders', 'Autistic Spectrum Disorders')], max_length=100)),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='biodata',
            name='nature_of_disability',
            field=models.ForeignKey(blank=True, default=None, max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nrb_data_api.disablednationalcouncil'),
        ),
    ]
